# Generated by Django 3.2.7 on 2021-10-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='telefono_celular',
            new_name='telefono_1',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefono_linea',
            new_name='telefono_2',
        ),
    ]
