# Generated by Django 3.2.7 on 2021-10-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_crud', '0002_auto_20211001_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='documento_numero',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
