# Generated by Django 3.2.7 on 2021-10-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_crud', '0003_alter_paciente_documento_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='afiliado',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='localidad',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacimiento_fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='plan',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profesion',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='referente',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_1',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_2',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
