# Generated by Django 3.2.7 on 2021-09-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptcrud', '0002_rename_modelo_naperson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Naperson',
            new_name='Narigon',
        ),
    ]
