# Generated by Django 3.2.9 on 2021-11-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('nacimientoFecha', models.DateField(null=True)),
                ('documentoNumero', models.CharField(max_length=20, null=True)),
                ('documentoTipo', models.CharField(choices=[('DNI', 'Documento de Identidad'), ('CI', 'Cedula de Identidad'), ('LE', 'Libreta de Enrolamiento'), ('LC', 'Libreta Civica')], default='DNI', max_length=3, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=2)),
                ('direccion', models.CharField(max_length=256, null=True)),
                ('localidad', models.CharField(max_length=128, null=True)),
                ('obraSocial', models.CharField(max_length=128, null=True)),
                ('plan', models.CharField(max_length=128, null=True)),
                ('afiliado', models.CharField(max_length=128, null=True)),
                ('telefono1', models.CharField(max_length=12, null=True)),
                ('telefono2', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('profesion', models.CharField(max_length=128, null=True)),
                ('referente', models.CharField(max_length=128, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
