# Generated by Django 3.2.9 on 2021-11-13 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_historiaclinica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='campo',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
