# Generated by Django 3.2.9 on 2021-11-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20211113_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='descripcion',
        ),
    ]
