# Generated by Django 3.2.9 on 2021-11-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20211117_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
