# Generated by Django 3.2.9 on 2021-11-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20211117_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
