# Generated by Django 3.2.9 on 2021-11-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20211117_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={},
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='id',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paciente.paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='descripcion',
            field=models.TextField(default='', null=True),
        ),
    ]
