# Generated by Django 3.2.9 on 2021-11-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_auto_20211118_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
