# Generated by Django 3.2.9 on 2021-12-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_alter_historiaclinica_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paciente.paciente')),
                ('Hipertension Arterial', models.BooleanField(default=False)),
                ('Diabetes Tipo I', models.BooleanField(default=False)),
                ('Diabetes Tipo 2', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='afiliado',
            field=models.CharField(max_length=128, null=True, verbose_name='Afiliado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=128, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=256, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='documentoNumero',
            field=models.CharField(max_length=20, null=True, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='documentoTipo',
            field=models.CharField(choices=[('DNI', 'Documento de Identidad'), ('CI', 'Cedula de Identidad'), ('LE', 'Libreta de Enrolamiento'), ('LC', 'Libreta Civica')], default='DNI', max_length=3, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=128, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=2, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='localidad',
            field=models.CharField(max_length=128, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacimientoFecha',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obraSocial',
            field=models.CharField(max_length=128, null=True, verbose_name='Obra Social'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='plan',
            field=models.CharField(max_length=128, null=True, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profesion',
            field=models.CharField(max_length=128, null=True, verbose_name='Profesion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='referente',
            field=models.CharField(max_length=128, null=True, verbose_name='Medico Referente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono1',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefono Celular'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono2',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefono Fijo'),
        ),
    ]
