# Generated by Django 3.2.9 on 2021-12-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_auto_20211206_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticos',
            name='Diabetes Tipo 2',
        ),
        migrations.RemoveField(
            model_name='diagnosticos',
            name='Diabetes Tipo I',
        ),
        migrations.RemoveField(
            model_name='diagnosticos',
            name='Hipertension Arterial',
        ),
        migrations.AddField(
            model_name='diagnosticos',
            name='diabetesT1',
            field=models.BooleanField(default=False, verbose_name='Diabetes Tipo I'),
        ),
        migrations.AddField(
            model_name='diagnosticos',
            name='diabetesT2',
            field=models.BooleanField(default=False, verbose_name='Diabetes Tipo 2'),
        ),
        migrations.AddField(
            model_name='diagnosticos',
            name='hipertensionArterial',
            field=models.BooleanField(default=False, verbose_name='Hipertension Arterial'),
        ),
    ]
