# Generated by Django 3.2.9 on 2021-12-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_auto_20211206_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticos',
            old_name='diabetesT1',
            new_name='diabetesI',
        ),
        migrations.RenameField(
            model_name='diagnosticos',
            old_name='diabetesT2',
            new_name='diabetesII',
        ),
    ]
