# Generated by Django 3.2.9 on 2021-12-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_auto_20211206_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticos',
            old_name='diabetesI',
            new_name='diabetes1',
        ),
        migrations.RenameField(
            model_name='diagnosticos',
            old_name='diabetesII',
            new_name='diabetes2',
        ),
        migrations.RenameField(
            model_name='diagnosticos',
            old_name='hipertensionArterial',
            new_name='hipertensionarterial',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='documentoNumero',
            new_name='documentonumero',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='documentoTipo',
            new_name='documentotipo',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nacimientoFecha',
            new_name='nacimientofecha',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='obraSocial',
            new_name='obrasocial',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefono1',
            new_name='telefonocelular',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefono2',
            new_name='telefonofijo',
        ),
    ]
