# Generated by Django 3.2.9 on 2022-01-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_auto_20211206_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='documentonumero',
            field=models.CharField(max_length=20, null=True, verbose_name='Nro Documento'),
        ),
    ]
